FROM php:8.4-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    nano \
    unzip \
    libzip-dev \
    libpng-dev \
    libonig-dev \
    libldap2-dev \
    supervisor \
    libssl-dev \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configurar la zona horaria (opcional, descomenta si lo necesitas)
# RUN ln -sf /usr/share/zoneinfo/America/Santiago /etc/localtime && \
#     dpkg-reconfigure -f noninteractive tzdata

# Instalar extensiones de PHP
RUN docker-php-ext-configure ldap --with-libdir=/lib/x86_64-linux-gnu && docker-php-ext-install pdo_mysql mbstring zip gd pgsql pdo_pgsql && docker-php-ext-enable pgsql pdo_pgsql

# Instalar Node.js 21
#RUN curl -fsSL https://deb.nodesource.com/setup_21.x  | bash - && apt-get install -y nodejs && node -v && npm -v

# Instalar Composer
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

# Copiar configuración personalizada de php.ini si es necesario
COPY php.ini /usr/local/etc/php/

# Copiar configuración de Supervisor
COPY supervisor/supervisor.conf /etc/supervisor/supervisord.conf

# Establecer directorio de trabajo
WORKDIR /var/www/html

 